# Generated by Django 4.1.7 on 2023-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
